# $HOME/.config/alacritty/alacritty.toml

live_config_reload = true

[font]
size = 10.0

[window]
decorations = "none"

dimensions = { columns = 140, lines = 40 }

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
