mklink %USERPROFILE%\.gitconfig %CD%\.gitconfig
mklink %USERPROFILE%\.gitconfig.user_personal %CD%\.gitconfig.user_personal
mklink %USERPROFILE%\.gitconfig.user_work %CD%\.gitconfig.user_work
mklink %USERPROFILE%\.gitconfig.message %CD%\.gitconfig.message
mklink %USERPROFILE%\.gitconfig.alias_basic %CD%\.gitconfig.alias_basic
mklink %USERPROFILE%\.gitconfig.alias_ignore %CD%\.gitconfig.alias_ignore
mklink %USERPROFILE%\.gitconfig.alias_log %CD%\.gitconfig.alias_log
mklink %USERPROFILE%\.gitconfig.alias_tree %CD%\.gitconfig.alias_tree
mklink %USERPROFILE%\.gitconfig.alias_misc %CD%\.gitconfig.alias_misc
