mklink %USERPROFILE%\.gitconfig %CD%\.gitconfig
mklink %USERPROFILE%\user_personal.gitconfig %CD%\user_personal.gitconfig
mklink %USERPROFILE%\user_work.gitconfig %CD%\user_work.gitconfig
mklink %USERPROFILE%\message.gitconfig %CD%\message.gitconfig
mklink %USERPROFILE%\alias_basic.gitconfig %CD%\alias_basic.gitconfig
mklink %USERPROFILE%\alias_ignore.gitconfig %CD%\alias_ignore.gitconfig
mklink %USERPROFILE%\alias_log.gitconfig %CD%\alias_log.gitconfig
mklink %USERPROFILE%\alias_tree.gitconfig %CD%\alias_tree.gitconfig
mklink %USERPROFILE%\alias_misc.gitconfig %CD%\alias_misc.gitconfig
