ln -s $PWD/.gitconfig $HOME/.gitconfig
ln -s $PWD/.gitconfig.user_personal $HOME/.gitconfig.user_personal
ln -s $PWD/.gitconfig.user_work $HOME/.gitconfig.user_work
ln -s $PWD/.gitconfig.message $HOME/.gitconfig.message
ln -s $PWD/.gitconfig.alias_basic $HOME/.gitconfig.alias_basic
ln -s $PWD/.gitconfig.alias_ignore $HOME/.gitconfig.alias_ignore
ln -s $PWD/.gitconfig.alias_log $HOME/.gitconfig.alias_log
ln -s $PWD/.gitconfig.alias_tree $HOME/.gitconfig.alias_tree
ln -s $PWD/.gitconfig.alias_misc $HOME/.gitconfig.alias_misc
