#!/bin/bash
#echo "Loading ~/.bash_alises"

# Basics
alias h='history'
alias hu='history -a;history -n'
alias hl='history | tail -n 30'
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias llm='ls -la | more'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  if [ -r ~/.dircolors ]; then
    eval "$(dircolors -b ~/.dircolors)"
  else
    eval "$(dircolors -b)"
  fi
  alias l='ls --color=auto'
  alias ls='ls --color=auto'
  #alias dir='dir --color=auto'
  #alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

if command -v "eza" >/dev/null; then
  alias l=eza
  alias l='eza -lbF --git'
  alias ll='eza -lbGF --git'
  alias llm='eza -lbGd --git --sort=modified'
  alias la='eza -lbhHigUmuSa --time-style=long-iso --git --color-scale'
  alias lx='eza -lbhHigUmuSa@ --time-style=long-iso --git --color-scale'

  # specialty views
  alias lS='eza -1'
  alias lt='eza --tree --level=2'
  alias l.="eza -a | grep -E '^\.'"
fi

# Editors
alias c='code' # already in PATH
if [[ -n "${WSL_DISTRO_NAME}" ]]; then
  alias ci='/mnt/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/bin/code-insiders'
else
  alias ci='/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/bin/code-insiders'
fi
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias t='tmux'

# Git
alias wip='git add -A && git commit -m "WIP: non-verifed - $(date +%Y-%m-%dT%H:%M:%S)" --no-verify'
alias vwip='git add -A && git commit -m "WIP: verified - $(date +%Y-%m-%dT%H:%M:%S)" --verify'

# Misc
alias mc='mc --nosubshell'
alias rtree='tree -I .git -a'
alias wttr='curl wttr.in/Janowice+Wielkie'


if command -v "batcat" >/dev/null && ! command -v "bat" >/dev/null; then
  alias bat=batcat
fi
