#!/bin/bash
#echo "Loading ~/.bash_alises"

# Basics
alias h='history'
alias hu='history -a;history -n'
alias hl='history | tail -n 30'
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias llm='ls -la | more'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  if [ -r ~/.dircolors ]; then
    eval "$(dircolors -b ~/.dircolors)"
  else
    eval "$(dircolors -b)"
  fi
  alias l='ls --color=auto'
  alias ls='ls --color=auto'
  #alias dir='dir --color=auto'
  #alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

if command -v "eza" >/dev/null; then
  alias l='pwd && eza -lbF --git'
  alias ll='pwd && eza -lbhgUmu --time-style=long-iso --git --color-scale'
  alias la='pwd && eza -lbhgUmu --all --time-style=long-iso --git --color-scale'
  alias lx='pwd && eza -lbhHigUmuS@ --all --time-style=long-iso --git --color-scale'
  alias lt='pwd && eza --tree --git-ignore --all'
  alias ltd='pwd && eza --tree --git-ignore --only-dirs'
  alias ltx='pwd && eza --tree --all'
  alias lS='pwd && eza -1'
  alias l.="pwd && eza -a | grep -E '^\.'"
fi

# Editors
alias co='code' # already in PATH
if [[ -n "${WSL_DISTRO_NAME}" ]]; then
  alias ci='/mnt/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/bin/code-insiders'
else
  alias ci='/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/bin/code-insiders'
fi
alias or='cursor'
alias v='nvim'
alias t='tmux'

# Misc
if command -v "gio" > /dev/null; then
  alias fm='gio open'
  fi
alias mc='mc --nosubshell'
alias rtree='tree -I .git -a'
alias wttr='curl wttr.in/Janowice+Wielkie'

if command -v "batcat" >/dev/null && ! command -v "bat" >/dev/null; then
  alias bat=batcat
fi
