"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](bg:yellow fg:peach)\
$env_var\
$mise\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$golang\
$lua\
$python\
$rust\
[](fg:teal bg:sapphire)\
$azure\
[](fg:sapphire bg:blue)\
$kubernetes\
[](fg:blue bg:blue)\
$docker_context\
[](fg:blue bg:surface0)\
$cmd_duration\
[ ](fg:surface0)\
$line_break$character"""

palette = 'catppuccin_mocha'

# Colors sorted by hue
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
format = '[ $user ]($style)'
show_always = true
style_root = "bg:surface0 fg:text"
style_user = "bg:surface0 fg:text"

[directory]
format = "[ $path ]($style)"
style = "fg:mantle bg:peach"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Developer" = "󰲋 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[env_var]

[env_var.MISE]
variable = "MISE_ENV"
format = '[[$symbol $env_value ](fg:base bg:yellow)]($style)'
style = "bg:teal"
symbol = ""

[mise]
disabled = false
format = '[[$symbol](fg:base bg:yellow)]($style)'
style = "bg:green"
symbol = "󱁤"
healthy_symbol = ""
unhealthy_symbol = ""

[git_branch]
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'
style = "bg:teal"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'
style = "bg:teal"

[c]
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
style = "bg:teal"
symbol = " "

[golang]
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
style = "bg:teal"
symbol = ""

[lua]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
style = "bg:teal"
symbol = ""

[rust]
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
style = "bg:teal"
symbol = ""

[azure]
disabled = false
format = '[$symbol($subscription)]($style)'
style = "fg:mantle bg:sapphire"
symbol = '󰠅 '

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
style = "fg:mantle bg:blue"
symbol = '⎈ '

[docker_context]
disabled = false
format = '[[ $symbol( $context) ](fg:#83a598 bg:blue)]($style)'
style = "bg:mantle"
symbol = ""

[time]
disabled = false
format = '[[  $time ](fg:mantle bg:purple)]($style)'
style = "bg:color_bg1"
time_format = "%R"

[cmd_duration]
format = '[  $duration]($style)'
min_time = 500
style = "bg:surface0 fg:text"

[line_break]
disabled = false

[character]
disabled = false
error_symbol = '[](bold fg:red)'
success_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
