[[session]]
name = "azure-hosting"
path = "~/azure-hosting"
startup_script = "~/.config/sesh/scripts/azure-hosting.sh"

[[session]]
name = "azure-hosting-infrastructure"
path = "~/azure-hosting-infrastructure"
startup_script = "~/.config/sesh/scripts/azure-hosting-az.sh"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_script = "~/.config/sesh/scripts/dotfiles.sh"