[[session]]
name = "cadcorp-cloud-prd"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-prd.sh"

[[session]]
name = "cadcorp-cloud-svc"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-svc.sh"

[[session]]
name = "cadcorp-cloud-tst"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-tst.sh"

[[session]]
name = "cadcorp-cloud-watch"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-watch.sh"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "~/.config/sesh/scripts/dotfiles.sh"
