[[session]]
name = "cadcorp-cloud-prd"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-prd.sh"

[[session]]
name = "cadcorp-cloud-svc"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-svc.sh"

[[session]]
name = "cadcorp-cloud-tst"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-tst.sh"

[[session]]
name = "cadcorp-cloud-watch-events"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-watch-events.sh"

[[session]]
name = "cadcorp-cloud-watch-pods"
path = "~/cadcorp-cloud"
startup_command = "~/.config/sesh/scripts/cadcorp-cloud-watch-pods.sh"


[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "~/.config/sesh/scripts/dotfiles.sh"
