# Git
alias g='git'
alias gad='git add'
alias gada='git add -A'
alias gbr='git branch'
alias gbra='git branch -a'
alias gbrv='git branch -vv'
alias gci='git commit'
alias gcia='git commit --amend'
alias gciae='git commit --amend --no-edit'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gcpm='git cherry-pick -x -e -m1'
alias gcpx='git cherry-pick -x -e'
alias gdf='git diff'
alias gdfc='git diff --cached'
alias ghs='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias gl='git log --color --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gla='git log --color --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --all'
alias glo='git log  --color --graph --oneline --date=iso'
alias gmb='git merge --log --no-ff'
alias gpl='git pull'
alias gps='git push'
alias grs='git reset'
alias grt='git remote -v'
alias gsh='git show'
alias gst='git status'
alias gsts='git submodule status'
alias gsw='git switch'
alias gwo='git show --date=iso --pretty=fuller --show-signature --no-patch'
alias fork='/mnt/c/Windows/System32/cmd.exe /c "%USERPROFILE%\AppData\Local\Fork\Fork.exe "$(wslpath -w -a .)'
alias lgit='lazygit'

# Azure CLI
alias a='az'

# Kubernetes
alias k='kubectl'
alias kci='kubectl cluster-info'
alias kd='kubectl destribe'
alias kdn='kubectl describe nodes'
alias kdnz='kubectl describe nodes | grep -e "Name:" -e "topology.kubernetes.io/zone"'
alias kl='kubectl logs'
alias kn='kubectl get nodes'
alias knw='kubectl get nodes -o wide'
alias kp='kubectl get pods'
alias kpw='kubectl get pods -o wide'
alias kv='kubectl version'
