views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
    - AGE
    - NAMESPACE
    - NAME
    - PF
    - READY
    - STATUS
    - RESTARTS
    - NODE
    - IP
    - CPU
    - MEM
  v1/pods@customer-*:
    sortColumn: AGE:asc
    columns:
    - AGE
    - STATUS
    - READY
    - RESTARTS
    - NAME
    - NAMESPACE
    - UCID:.metadata.annotations.cadcorp\.cloud/ucid
    - NODE
  customers:
    sortColumn: AGE:asc
    columns:
    - AGE
    - STATUS
    - READY
    - RESTARTS
    - NAME
    - NAMESPACE
    - UCID:.metadata.annotations.cadcorp\.cloud/ucid
    - NODE
